# jacoco-badge-generator: Coverage badges, and pull request coverage checks, 
# from JaCoCo reports in GitHub Actions
# 
# Copyright (c) 2020-2025 Vincent A Cicirello
# https://www.cicirello.org/
#
# MIT License
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 


name: 'jacoco-badge-generator'
description: 'JaCoCo coverage badges and pull request coverage checks in GitHub Actions'
branding: 
  icon: 'book-open'
  color: 'green'
inputs:
  jacoco-csv-file:  
    description: 'Full path, relative to the root of the repository, to the jacoco csv file(s), including filename(s)'
    required: false
    default: 'target/site/jacoco/jacoco.csv'
  badges-directory:
    description: 'The directory for storing badges, relative to the root of the repository.'
    required: false
    default: '.github/badges'
  coverage-badge-filename:
    description: 'The filename of the coverage badge.'
    required: false
    default: 'jacoco.svg'
  branches-badge-filename:
    description: 'The filename of the branches coverage badge.'
    required: false
    default: 'branches.svg'
  generate-coverage-badge:
    description: 'Controls whether or not to generate the coverage badge.'
    required: false
    default: true
  generate-branches-badge:
    description: 'Controls whether or not to generate the branches coverage badge.'
    required: false
    default: false
  coverage-label:
    description: 'Text for the left-side of the coverage badge.'
    required: false
    default: coverage
  branches-label:
    description: 'Text for the left-side of the branches coverage badge.'
    required: false
    default: branches
  on-missing-report:
    description: 'Controls what happens if one or more jacoco.csv files do not exist.'
    required: false
    default: 'fail'
  fail-if-coverage-less-than:
    description: 'Enables failing workflow run when coverage below specified threshold.'
    required: false
    default: 0
  fail-if-branches-less-than:
    description: 'Enables failing workflow run when branches coverage below specified threshold.'
    required: false
    default: 0
  fail-on-coverage-decrease:
    description: 'Enables failing workflow if coverage is less than it was on previous run.'
    required: false
    default: false
  fail-on-branches-decrease:
    description: 'Enables failing workflow if branches coverage is less than it was on previous run.'
    required: false
    default: false
  coverage-decrease-limit:
    description: 'Overrides fail-on-coverage-decrease when coverage is at least this limit'
    required: false
    default: 100
  branches-decrease-limit:
    description: 'Overrides fail-on-branches-decrease when branches coverage is at least this limit'
    required: false
    default: 100
  intervals:
    description: 'List of coverage percentages as cutoffs for each color.'
    required: false
    default: 100 90 80 70 60 0
  colors:
    description: 'List of colors to use ordered by coverage interval, best coverage to worst.'
    required: false
    default: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
  generate-coverage-endpoint:
    description: 'Controls whether or not to generate the coverage JSON endpoint.'
    required: false
    default: false
  generate-branches-endpoint:
    description: 'Controls whether or not to generate the branches coverage JSON endpoint.'
    required: false
    default: false
  coverage-endpoint-filename:
    description: 'The filename of the coverage JSON endpoint.'
    required: false
    default: 'jacoco.json'
  branches-endpoint-filename:
    description: 'The filename of the branches coverage JSON endpoint.'
    required: false
    default: 'branches.json'
  generate-summary:
    description: 'Controls whether or not to generate a JSON file containing the coverage percentages as floating-point values.'
    required: false
    default: false
  summary-filename:
    description: 'The filename of the summary file.'
    required: false
    default: 'coverage-summary.json'
  generate-workflow-summary:
    description: 'Controls whether or not to append summary to the GitHub workflow summary page.'
    required: false
    default: true
  workflow-summary-heading:
    description: 'The heading for the GitHub workflow job summary'
    required: false
    default: JaCoCo Test Coverage Summary
outputs:
  coverage:
    description: 'The jacoco coverage percentage as computed from the data in the jacoco.csv file.'
  branches:
    description: 'The jacoco branch coverage percentage as computed from the data in the jacoco.csv file.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jacoco-csv-file }}
    - ${{ inputs.badges-directory }}
    - ${{ inputs.coverage-badge-filename }}
    - ${{ inputs.branches-badge-filename }}
    - ${{ inputs.generate-coverage-badge }}
    - ${{ inputs.generate-branches-badge }}
    - ${{ inputs.on-missing-report }}
    - ${{ inputs.fail-if-coverage-less-than }}
    - ${{ inputs.fail-if-branches-less-than }}
    - ${{ inputs.fail-on-coverage-decrease }}
    - ${{ inputs.fail-on-branches-decrease }}
    - ${{ inputs.intervals }}
    - ${{ inputs.colors }}
    - ${{ inputs.generate-coverage-endpoint }}
    - ${{ inputs.generate-branches-endpoint }}
    - ${{ inputs.coverage-endpoint-filename }}
    - ${{ inputs.branches-endpoint-filename }}
    - ${{ inputs.generate-summary }}
    - ${{ inputs.summary-filename }}
    - ${{ inputs.generate-workflow-summary }}
    - ${{ inputs.coverage-label }}
    - ${{ inputs.branches-label }}
    - ${{ inputs.workflow-summary-heading }}
    - ${{ inputs.coverage-decrease-limit }}
    - ${{ inputs.branches-decrease-limit }}
